[package]
name = "hyprland-keybinds"
version = "0.1.0"
edition = "2021"
description = "GTK4 app to display keybinds from Hyprland config"

[dependencies]
gtk = { version = "0.9", package = "gtk4" }
glib = "0.18.0"
once_cell = "1.18"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
regex = "1.10"
