[templates]
css = { path = "/home/sd-v/.config/hypr/colorgen/colors.css" }
hyprland = { path = "/home/sd-v/.config/hypr/colorgen/colors.conf" }

[material]
# Ensure tonal range extends properly from color to white
tone_percentages = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 99, 100]
